### ISSUE TITLE
Coordinate transform error

### ISSUE THREAD

**Issue by sunshine0576** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#113]
2017-11-08T14:56:58	1	Traceback (most recent call last):
			  File "C:/Users/PC8651/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 886, in _on_timeout
			    should_notify = self._predicate()
			  File "C:/Users/PC8651/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 200, in _have_extent_or_scale_changed
			    has_extent_changed = self._has_extent_changed()[0]
			  File "C:/Users/PC8651/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 235, in _has_extent_changed
			    new_extent = self._get_visible_extent_as_tile_bounds(scheme, zoom)
			  File "C:/Users/PC8651/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 393, in _get_visible_extent_as_tile_bounds
			    max_proj = epsg3857_to_wgs84_lonlat(max_extent[0], max_extent[1])
			  File "C:/Users/PC8651/.qgis2/python/plugins\vector_tiles_reader\tile_helper.py", line 120, in epsg3857_to_wgs84_lonlat
			    wgs84 = gm.MetersToLatLon(x, y)
			  File "C:/Users/PC8651/.qgis2/python/plugins\vector_tiles_reader\global_map_tiles.py", line 196, in MetersToLatLon
			    lat = 180 / math.pi * (2 * math.atan(math.exp(lat * math.pi / 180.0)) - old_div(math.pi, 2.0))
			OverflowError: math range error
			
2017-11-08T14:57:02	1	Traceback (most recent call last):
			  File "C:/Users/PC8651/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 886, in _on_timeout
			    should_notify = self._predicate()
			  File "C:/Users/PC8651/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 200, in _have_extent_or_scale_changed
			    has_extent_changed = self._has_extent_changed()[0]
			  File "C:/Users/PC8651/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 235, in _has_extent_changed
			    new_extent = self._get_visible_extent_as_tile_bounds(scheme, zoom)
			  File "C:/Users/PC8651/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 393, in _get_visible_extent_as_tile_bounds
			    max_proj = epsg3857_to_wgs84_lonlat(max_extent[0], max_extent[1])
			  File "C:/Users/PC8651/.qgis2/python/plugins\vector_tiles_reader\tile_helper.py", line 120, in epsg3857_to_wgs84_lonlat
			    wgs84 = gm.MetersToLatLon(x, y)
			  File "C:/Users/PC8651/.qgis2/python/plugins\vector_tiles_reader\global_map_tiles.py", line 196, in MetersToLatLon
			    lat = 180 / math.pi * (2 * math.atan(math.exp(lat * math.pi / 180.0)) - old_div(math.pi, 2.0))
			OverflowError: math range error

**Comment by sfkeller** [comment]
Can you privide us with the source in order to test it? 
A remote connection requires a TileJSON 2 spec
https://github.com/mapbox/tilejson-spec/tree/master/2.2.0 .
Remind that coordinate transformation is not yet implemented.

**Comment by sunshine0576** [comment]
I  use default connection (openMapTiles.com).
when i move and zoom map.The plug-in crashed。
Remarks：my map srs is 4326.

**Comment by mnboos** [comment]
Can you set the map srs in QGIS to 3857 and try again please?

**Comment by sunshine0576** [comment]
I unable to reproduce when  use QGIS  3857

**Comment by mnboos** [comment]
Could you show me the log from the crash please?

**Comment by mnboos** [comment]
With the next release, this should also be fixed. Or at least it shouldn't crash.
