### ISSUE TITLE
Error loading Klokantech's sample

### ISSUE THREAD

**Issue by kannes** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#117]
When I load the https://github.com/klokantech/vector-tiles-sample/releases/download/v1.0/countries.mbtiles from https://github.com/klokantech/vector-tiles-sample all I see is some part of Africa (sometimes other regions) and the following Python error:

```
Traceback (most recent call last):
  File "/home/me/.qgis2/python/plugins/vector_tiles_reader/vtr_plugin.py", line 886, in _on_timeout
    should_notify = self._predicate()
  File "/home/me/.qgis2/python/plugins/vector_tiles_reader/vtr_plugin.py", line 200, in _have_extent_or_scale_changed
    has_extent_changed = self._has_extent_changed()[0]
  File "/home/me/.qgis2/python/plugins/vector_tiles_reader/vtr_plugin.py", line 237, in _has_extent_changed
    new_extent = clamp_bounds(new_extent, bounds)
  File "/home/me/.qgis2/python/plugins/vector_tiles_reader/tile_helper.py", line 43, in clamp_bounds
    x_min = clamp(bounds_to_clamp["x_min"], low=clamp_values["x_min"])
TypeError: 'NoneType' object has no attribute '__getitem__'

```

QGIS 2.18.3
VTR Plugin 1.2.3

**Comment by mnboos** [comment]
That's because "bounds" in metadata is missing. Good news is, I fixed that already and it will be included in the next release.

**Comment by kannes** [comment]
Excellent!
