### ISSUE TITLE
Cannot convert float NaN to integer

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#130]
I'm getting this every so often. Latest instance was that I had an existing non-VT project open, and added Mapzen VT to it:

```
ValueError: cannot convert float NaN to integer 
Traceback (most recent call last):
  File "C:/Users/tchadwin/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 918, in _on_timeout
    should_notify = self._predicate()
  File "C:/Users/tchadwin/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 220, in _have_extent_or_scale_changed
    has_extent_changed = self._has_extent_changed()[0]
  File "C:/Users/tchadwin/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 406, in _has_extent_changed
    new_extent = self._get_visible_extent_as_tile_bounds(scheme, zoom)
  File "C:/Users/tchadwin/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 513, in _get_visible_extent_as_tile_bounds
    tile_bounds = get_tile_bounds(zoom, bounds=bounds, scheme=scheme, source_crs=current_crs)
  File "C:/Users/tchadwin/.qgis2/python/plugins\vector_tiles_reader\util\tile_helper.py", line 176, in get_tile_bounds
    xy_min = latlon_to_tile(zoom=zoom, lat=lat_min, lng=lng_min, source_crs=source_crs, scheme=scheme)
  File "C:/Users/tchadwin/.qgis2/python/plugins\vector_tiles_reader\util\tile_helper.py", line 114, in latlon_to_tile
    col, row = gm.MetersToTile(mx=mx, my=my, zoom=zoom)
  File "C:/Users/tchadwin/.qgis2/python/plugins\vector_tiles_reader\util\global_map_tiles.py", line 232, in MetersToTile
    return self.PixelsToTile(px, py)
  File "C:/Users/tchadwin/.qgis2/python/plugins\vector_tiles_reader\util\global_map_tiles.py", line 219, in PixelsToTile
    ty = int(math.ceil(old_div(py, float(self.tileSize))) - 1)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\future\backports\misc.py", line 34, in ceil
    return int(oldceil(x))
ValueError: cannot convert float NaN to integer
```

**Comment by tomchadwin** [comment]
Possibly because non-3857. Will just upgrade - saw you added CRS support.

**Comment by tomchadwin** [comment]
Maybe fixed by using master. Will close for now.
