### ISSUE TITLE
Error  if disconnect and reconnect

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#131]
I experience this if I hibernate my laptop and then wake it up again:

```
QgsCsException: forward transform of (2860713.981007, 15315335.214768) PROJ.4:  +proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +datum=NAD27 +units=us-ft +no_defs +ellps=clrk66 +nadgrids=@conus,@alaska,@ntv2_0.gsb,@ntv1_can.dat +to  +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 Error: tolerance condition error 
Traceback (most recent call last):
  File "C:/Users/tchadwin/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 452, in _handle_mouse_move
    x, y = latlon_to_tile(zoom=zoom, lat=lat, lng=lon, source_crs=current_crs)
  File "C:/Users/tchadwin/.qgis2/python/plugins\vector_tiles_reader\util\tile_helper.py", line 107, in latlon_to_tile
    lng, lat = convert_coordinate(source_crs=source_crs, target_crs=4326, lat=lat, lng=lng)
  File "C:/Users/tchadwin/.qgis2/python/plugins\vector_tiles_reader\util\tile_helper.py", line 130, in convert_coordinate
    x, y = xform.transform(QgsPoint(lng, lat))
QgsCsException: forward transform of
(2860713.981007, 15315335.214768)
PROJ.4:  +proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +datum=NAD27 +units=us-ft +no_defs +ellps=clrk66 +nadgrids=@conus,@alaska,@ntv2_0.gsb,@ntv1_can.dat +to  +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0
Error: tolerance condition error
```

**Comment by mnboos** [comment]
That looks more like a QGIS error, only triggered by the plugin.

```python
xform = QgsCoordinateTransform(crs_src, crs_dest)
x, y = xform.transform(QgsPoint(lng, lat))
```

**Comment by sfkeller** [comment]
@m-kuhn: Do you have an idea if this is a QGIS error?

**Comment by tomchadwin** [comment]
That error indicates a vertex closer to the pole than is supported by the projection. I don't see what that has to do disconnect/reconnect, so I'll try to get more specific info. Can anyone else recreate the issue?

**Comment by m-kuhn** [comment]
It's triggered inside proj.4, probably caused by bogus parameters. A mispositioned vertex sounds plausible, but I can neither confirm nor deny this.

**Comment by sfkeller** [comment]
@tomchadwin : Can you reproduce this error? Did you test the same with differnent VT sources (OpenMapTiles connection, Mapzen connection, or even mbtiles file)? 
I fear, that if the bug is not reproducible elsewhere, we have to close it for now.

**Comment by tomchadwin** [comment]
I've just tested again, and cannot recreate, so I'll close. Thanks.

**Comment by tomchadwin** [comment]
I won't reopen, but I've just had this again with 1.3.0:

```
ValueError: cannot convert float NaN to integer 
Traceback (most recent call last):
  File "C:/Users/tchadwin/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 452, in _handle_mouse_move
    x, y = latlon_to_tile(zoom=zoom, lat=lat, lng=lon, source_crs=current_crs)
  File "C:/Users/tchadwin/.qgis2/python/plugins\vector_tiles_reader\util\tile_helper.py", line 114, in latlon_to_tile
    col, row = gm.MetersToTile(mx=mx, my=my, zoom=zoom)
  File "C:/Users/tchadwin/.qgis2/python/plugins\vector_tiles_reader\util\global_map_tiles.py", line 232, in MetersToTile
    return self.PixelsToTile(px, py)
  File "C:/Users/tchadwin/.qgis2/python/plugins\vector_tiles_reader\util\global_map_tiles.py", line 219, in PixelsToTile
    ty = int(math.ceil(old_div(py, float(self.tileSize))) - 1)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\future\backports\misc.py", line 34, in ceil
    return int(oldceil(x))
ValueError: cannot convert float NaN to integer
```
