### ISSUE TITLE
ImportError: No module named shapely.geometry.base

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#16]
Triggered when I click "Open" in the plugin dialog box:

```
ImportError: No module named shapely.geometry.base 
Traceback (most recent call last):
  File "C:/Users/tchadwin/.qgis2/python/plugins\Vector-Tiles-Reader-QGIS-Plugin\vtr_plugin.py", line 57, in _update_zoom_from_file
    reader = self._create_reader(path)
  File "C:/Users/tchadwin/.qgis2/python/plugins\Vector-Tiles-Reader-QGIS-Plugin\vtr_plugin.py", line 160, in _create_reader
    from vt_reader import VtReader
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/tchadwin/.qgis2/python/plugins\Vector-Tiles-Reader-QGIS-Plugin\vt_reader.py", line 15, in 
    import mapbox_vector_tile
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\tchadwin\.qgis2\python\plugins\Vector-Tiles-Reader-QGIS-Plugin\ext-libs\mapbox_vector_tile\__init__.py", line 1, in 
    from . import encoder
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\tchadwin\.qgis2\python\plugins\Vector-Tiles-Reader-QGIS-Plugin\ext-libs\mapbox_vector_tile\encoder.py", line 6, in 
    from shapely.geometry.base import BaseGeometry
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named shapely.geometry.base
```

**Comment by tomchadwin** [comment]
This is under Win7x64. Solved by downloading Shapely wheel and doing `pip install`. Probably need to add as a prerequisite, as I don't think there is any mechanism to install as part of the QGIS plugin.

**Comment by mnboos** [comment]
I added shapely as included dependency. Would be happy if you could test it in your environment.  Just clone the master branch.

**Comment by tomchadwin** [comment]
Will do. How do I manually uninstall a wheel? I'll find out.

**Comment by mnboos** [comment]
I manually deleted the shapely folder in C:\Program Files\QGIS 2.18\apps\Python27\lib\site-packages.
Not sure if that's the way to go.

**Comment by tomchadwin** [comment]
Fix confirmed - thanks.
