### ISSUE TITLE
"Exception: unknown" thrown by: x, y = xform.transform(QgsPoint(lng, lat))

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#198]
```
An error has occurred while executing Python code: 

Exception: unknown 
Traceback (most recent call last):
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\vtr_plugin.py", line 534, in _handle_mouse_move
    x, y = latlon_to_tile(zoom=zoom, lat=lat, lng=lon, source_crs=current_crs)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\util\tile_helper.py", line 110, in latlon_to_tile
    lng, lat = convert_coordinate(source_crs=source_crs, target_crs=3857, lat=lat, lng=lng)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\util\tile_helper.py", line 134, in convert_coordinate
    x, y = xform.transform(QgsPoint(lng, lat))
Exception: unknown


Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.0.1-Girona Girona, a86bec25eb 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python36.zip
C:\OSGEO4~1\apps\Python36\DLLs
C:\OSGEO4~1\apps\Python36\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python36
C:\OSGEO4~1\apps\Python36\lib\site-packages
C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\tchadwin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\tchadwin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\tchadwin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs
```

Just updated the plugin via the plugin manager, so v2.0.0.

**Comment by mnboos** [comment]
Thanks for the report. Unfortunately, I cannot reproduce the problem, neither in Windows nor in Ubuntu. Does that happen all the time or only at the installation? Is the plugin usable otherwise?

**Comment by tomchadwin** [comment]
I can't now reproduce, but I wonder if my project was in a different CRS. I'll close, but comment again if it reoccurs.

**Comment by mnboos** [comment]
Yes please keep me updated! Thanks for testing.
