### ISSUE TITLE
Error adding layers after connection to OpenMapTiles has been made

### ISSUE THREAD

**Issue by emsyvn** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#215]
After connecting to OpenMapTiles and clicking "Add" to add a layer, the following Python error occurs:

"An error has occurred while executing Python code: 
TypeError: '>' not supported between instances of 'NoneType' and 'int' "

The connection is successful and the layers are shown, but the error occurs as soon as I click "Add".

**Comment by mnboos** [comment]
Which operating system are you using and which version of QGIS?

**Comment by mnboos** [comment]
Note to me: This is most probably caused by this line https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/blob/8f82c9903d4d53b0d33c24a72493680864524722/ui/dialogs.py#L296

To be clarified, how this can happen

**Comment by ghost** [comment]
Hey, any updates on this? I have the same problem with QGIS version 3.2 (Bonn) under macOS 10.14.
With QGIS 3.6 there's no problem with this message, but not a single features is being added. The groups appear in the layer overview, but not the features.

Thank you!

**Comment by mnboos** [comment]
Could you show me the content of the logfile? Or the logs from the logpanel within QGIS.

**Comment by ghost** [comment]
**1. Error message in QGIS 3.2**

An error has occurred while executing Python code: 

> TypeError: '>' not supported between instances of 'NoneType' and 'int' 
> Traceback (most recent call last):
>   File "/Users/Florian/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/ui/dialogs.py", line 296, in _load_tiles_for_connection
>     if self._nr_of_tiles > threshold and not self.options.tile_number_limit():
> TypeError: '>' not supported between instances of 'NoneType' and 'int'
> 
> 
> Python version: 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
> QGIS version: 3.2.3-Bonn Bonn, exported 
> 
> Python Path:
> /Applications/QGIS3.app/Contents/MacOS/../Resources/python
> /Users/Florian/Library/Application Support/QGIS/QGIS3/profiles/default/python
> /Users/Florian/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
> /Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
> /Library/Frameworks/SQLite3.framework/Versions/E/Python/3.6
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
> /Users/Florian/Library/Application Support/QGIS/QGIS3/profiles/default/python
> /Users/Florian/CloudStation/Dokumente/Firma/Poster/QGIS/alle_städte
> /Users/Florian/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/ext-libs

**2. Log message in QGIS 3.2**

> 2019-03-12T15:32:27     WARNING    Traceback (most recent call last):
>               File "/Users/Florian/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/vtr_plugin.py", line 542, in _handle_mouse_move
>               current_crs = self._get_qgis_crs()
>               File "/Users/Florian/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/vtr_plugin.py", line 528, in _get_qgis_crs
>               return get_code_from_epsg(canvas.mapSettings().destinationCrs().authid())
>               File "/Users/Florian/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/util/tile_helper.py", line 142, in get_code_from_epsg
>               return int(code)
>              ValueError: invalid literal for int() with base 10: 'USER:100000'
> 

**3. Log message QGIS 3.6**

> 2019-03-12T15:34:06     WARNING    Vector Tiles Reader (Python 3.6.8)
> 2019-03-12T15:34:06     WARNING    URL check for 'https://maps.tilehosting.com/data/uk-openzoomstack.json status '200'
> 2019-03-12T15:34:06     WARNING    URL check for 'https://maps.tilehosting.com/data/uk-openzoomstack.json status '200'
> 2019-03-12T15:34:07     WARNING    Reloading due to scale change from 'None' (zoom None) to '75846616' (zoom 2)
> 2019-03-12T15:34:07     WARNING    Loading aborted as there are no layers of the current connection already loaded.
> 2019-03-12T15:35:12     WARNING    Shutdown reader
> 2019-03-12T15:35:12     WARNING    URL check for 'https://maps.tilehosting.com/data/v3.json status '200'
> 2019-03-12T15:35:12     WARNING    URL check for 'https://maps.tilehosting.com/data/v3.json status '200'
> 2019-03-12T15:35:38     WARNING    Creating styles from: https://maps.tilehosting.com/c/a0d98b43-86d2-424d-9941-4ada02661477/styles/posterlin2/style.json
> 2019-03-12T15:35:38     WARNING    URL check for 'https://maps.tilehosting.com/c/a0d98b43-86d2-424d-9941-4ada02661477/styles/posterlin2/style.json status '200'
> 2019-03-12T15:35:39     WARNING    Styles will be written to: /var/folders/0s/th8blg7n3ps1x6gfsqc3r64r0000gn/T/vector_tiles_reader/styles/posterlin5
> 2019-03-12T15:35:39     WARNING    Setting background color: #ffffff
> 2019-03-12T15:35:39     WARNING    Bounds of source: {'zoom': 2, 'x_min': 0, 'x_max': 3, 'y_min': 0, 'y_max': 3, 'width': 4, 'height': 4, 'scheme': 'xyz'}
> 2019-03-12T15:35:39     WARNING    Loading zoom level '2', bounds: {'zoom': 2, 'x_min': 0, 'x_max': 0, 'y_min': 0, 'y_max': 0, 'width': 1, 'height': 1, 'scheme': 'xyz'}
> 2019-03-12T15:35:39     WARNING    Native decoding supported!!!
> 2019-03-12T15:35:39     WARNING    Tile limit enabled: False
> 2019-03-12T15:35:39     WARNING    0 tiles in cache. Max. 1 will be loaded additionally.
> 2019-03-12T15:35:39     WARNING    Getting 1 tiles from source...
> 2019-03-12T15:35:39     WARNING    Error during network request: 201, https://maps.tilehosting.com/data/v3/2/0/0.pbf
> 2019-03-12T15:35:39     WARNING    Creating layers...
> 2019-03-12T15:35:39     WARNING    Refresh layers...
> 2019-03-12T15:35:39     WARNING    Import complete
> 2019-03-12T15:35:40     WARNING    Loading of zoom level 2 complete! No extent loaded.

**Comment by ghost** [comment]
Is there anything else I can provide you with?

**Comment by mnboos** [comment]
No, thanks! That's more than I hoped for. I'm currently preparing a release which fixes this issues. Especially nr. 3 is bad and must have found his way into the current release when I split up the branches for seperate QGIS 3 development.

**Comment by mnboos** [comment]
Ah, I didn't know issues are automatically closed through a PR. 

@nvfl600d I published release v3.0.1 a few minutes ago. It might take another few until it's available in QGIS. I would be happy, if you could give some feedback.

**Comment by ghost** [comment]
Thank you so much for your quick help and I hope that @emsyvn is also happy again, when this is going to be released! 

Sure thing, I'll test it and give you feedback. Have a nice day! :)

**Comment by mnboos** [comment]
Thanks you too! :)

**Comment by ghost** [comment]
It works under QGIS 3.6! Good job!

**Comment by mnboos** [comment]
Happy to hear, thanks!
