### ISSUE TITLE
GL style error in QGIS 3.4 - Style generation failed

### ISSUE THREAD

**Issue by vysmaty** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#216]
I am unable to get it work and I getting this in log:

[2019-01-02 09:54:20,029] [MainThread  ] [ERROR   ]  Style generation failed: (<class 'json.decoder.JSONDecodeError'>, JSONDecodeError('Expecting value: line 7 column 1 (char 6)'), <traceback object at 0x000001C351546C08>), Traceback (most recent call last):
  File "C:/Users/MartinRed/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\vtr_plugin.py", line 430, in _create_styles
    core.generate_styles(data, output_directory, web_request_executor=self._load_style_data)
  File "C:\Users\MartinRed\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs\mapboxstyle2qgis\core\__init__.py", line 50, in generate_styles
    styles = process(style_json)
  File "C:\Users\MartinRed\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs\mapboxstyle2qgis\core\__init__.py", line 83, in process
    style_json = json.loads(style_json)
  File "C:\PROGRA~1\QGIS 3.4\apps\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\PROGRA~1\QGIS 3.4\apps\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\PROGRA~1\QGIS 3.4\apps\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)
Traceback (most recent call last):
  File "C:/Users/MartinRed/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\vtr_plugin.py", line 430, in _create_styles
    core.generate_styles(data, output_directory, web_request_executor=self._load_style_data)
  File "C:\Users\MartinRed\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs\mapboxstyle2qgis\core\__init__.py", line 50, in generate_styles
    styles = process(style_json)
  File "C:\Users\MartinRed\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs\mapboxstyle2qgis\core\__init__.py", line 83, in process
    style_json = json.loads(style_json)
  File "C:\PROGRA~1\QGIS 3.4\apps\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\PROGRA~1\QGIS 3.4\apps\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\PROGRA~1\QGIS 3.4\apps\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)

**Comment by mnboos** [comment]
Thanks for the report!

Could you give me a link to the JSON style you are trying to use?

**Comment by vysmaty** [comment]
This one: https://raw.githubusercontent.com/openmaptiles/osm-bright-gl-style/master/style.json

**Comment by mnboos** [comment]
I tried with QGIS 3.4.3 and it worked perfectly with the style you linked. According to your stacktrace, I would guess it's somehow invalid json, as the decoding fails, which isn't my code.
Could you try once again please?

**Comment by vysmaty** [comment]
Thank you very much. I tried it once more and it did work eventually. I don't know what changed. I'm really sorry to bother you.

**Comment by mnboos** [comment]
Absolutly no problem.
