### ISSUE TITLE
Access is denied when upgrading plugin from 3.2.0 > 3.2.1

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#263]
```
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\tchadwin\\AppData\\Local\\Temp\\vector_tiles_reader\\native\\pbf2geojson_windows_x86_64.dll' 
Traceback (most recent call last):
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\vtr_plugin.py", line 390, in _on_connect
    reader = self._create_reader(connection=connection)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\vtr_plugin.py", line 833, in _create_reader
    reader = VtReader(self.iface, connection=connection)
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\vt_reader.py", line 101, in __init__
    load_lib()
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\util\mp_helper.py", line 69, in load_lib
    path = _get_lib_path()
  File "C:/Users/tchadwin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\util\mp_helper.py", line 56, in _get_lib_path
    os.remove(temp_lib_path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\tchadwin\\AppData\\Local\\Temp\\vector_tiles_reader\\native\\pbf2geojson_windows_x86_64.dll'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.8.3-Zanzibar Zanzibar, 685d8b15d2 
```

Seems to function fine afterwards.

**Comment by mnboos** [comment]
Okay, I see the problem. Thanks.
