### ISSUE TITLE
Error Loading Layer

### ISSUE THREAD

**Issue by ismailsunni** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#286]
I tried to load a mbtiles using this plugin on QGIS 3.10.11 on Windows 10. The data is coming from 

Data: https://osmlab.github.io/osm-qa-tiles/ (Switzerland)
GL Style JSON URL: https://raw.githubusercontent.com/openmaptiles/dark-matter-gl-style/master/style.json

The stack trace that I got:

```
2020-11-30T18:18:43     WARNING    Processing tiles in parallel...
2020-11-30T18:18:43     WARNING    An exception occured: [WinError 2] The system cannot find the file specified, Traceback (most recent call last):
              File "C:/Users/fclementi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\vt_reader.py", line 288, in _load_tiles
              tiles = self._decode_tiles(tile_data_tuples)
              File "C:/Users/fclementi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\vt_reader.py", line 437, in _decode_tiles
              pool = self._get_pool()
              File "C:/Users/fclementi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\vt_reader.py", line 406, in _get_pool
              pool = multiprocessing.Pool(nr_processors)
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\multiprocessing\context.py", line 119, in Pool
              context=self.get_context())
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\multiprocessing\pool.py", line 176, in __init__
              self._repopulate_pool()
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
              w.start()
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\multiprocessing\process.py", line 112, in start
              self._popen = self._Popen(self)
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\multiprocessing\context.py", line 322, in _Popen
              return Popen(process_obj)
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\multiprocessing\popen_spawn_win32.py", line 48, in __init__
              None, None, False, 0, None, None, None)
             FileNotFoundError: [WinError 2] The system cannot find the file specified
             
2020-11-30T18:18:43     WARNING    Loading cancelled
```

Is there anything that I missed?

**Comment by ismailsunni** [comment]
I just tried to install it on QGIS 3.10 and 3.16 on Ubuntu 18.04. Unfortunately, right after enabling the plugin, my QGIS crashes. Any idea about this issue?

**Comment by mnboos** [comment]
I'm afraid without a TileJSON url this is not going to work sorry.

**Comment by mnboos** [comment]
> I just tried to install it on QGIS 3.10 and 3.16 on Ubuntu 18.04. Unfortunately, right after enabling the plugin, my QGIS crashes. Any idea about this issue?

Can you retrieve a logfile maybe? Either from QGIS or from the plugin.

**Comment by ajl20** [comment]
> I just tried to install it on QGIS 3.10 and 3.16 on Ubuntu 18.04. Unfortunately, right after enabling the plugin, my QGIS crashes. Any idea about this issue?

> Can you retrieve a logfile maybe? Either from QGIS or from the plugin.

Similar crash with QGIS 3.18 and Ubuntu 20.04.  Appreciate the following is inelegant but potentially useful: 

Running QGIS from command line, so errors logged to terminal whilst installed plugin:

$ qgis
QGIS died on signal 11Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No thread selected
No stack.
gdb returned 256
Aborted (core dumped)

and

$ sudo qgis
Warning: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'

but otherwise plugin installed.
