### ISSUE TITLE
Why does vtr keep displaying error and cannot get the openinframap data

### ISSUE THREAD

**Issue by mmmlynn** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#289]
No matter which version I use, 3.16, 3.18, 3.24, 3.28 or others, it will show 'RuntimeError: wrapped C/C++ object of type QgsMessageBarItem has been deleted'. Tell me I failed to get the data. Is this a plug-in error?
WARNING    Traceback (most recent call last):
              File "C:/Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\vtr_plugin.py", line 467, in reader_cancelled
              self.handle_progress_update(show_progress=False)
              File "C:/Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\vtr_plugin.py", line 957, in handle_progress_update
              self.iface.messageBar().popWidget(self.message_bar_item)
             RuntimeError: wrapped C/C++ object of type QgsMessageBarItem has been deleted
or:
 WARNING    Traceback (most recent call last):
              File "C:/Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\vtr_plugin.py", line 928, in reader_cancelled
              self.handle_progress_update(progress=progress)
              File "C:/Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\vtr_plugin.py", line 967, in handle_progress_update
             self.progress_bar.setValue(progress)
             RuntimeError: wrapped C/C++ object of type QgsMessageBarItem has been deleted
and:
 An exception occured: [WinError 2],The system cannot find the specified file.,Traceback (most recent call last):
              File "C:/Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\vt_reader.py", line 288, in _load_tiles
              tiles = self._decode_tiles(tile_data_tuples)
              File "C:/Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\vt_reader.py", line 437, in _decode_tiles
              pool = self._get_pool()
              File "C:/Users/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\vt_reader.py", line 406, in _get_pool
              pool = multiprocessing.Pool(nr_processors)
              File "D:\Program Files (x86)\QGIS\apps\Python37\lib\multiprocessing\context.py", line 119, in Pool
              context=self.get_context())
              File "D:\Program Files (x86)\QGIS\apps\Python37\lib\multiprocessing\pool.py", line 176, in __init__
              self._repopulate_pool()
              File "D:\Program Files (x86)\QGIS\apps\Python37\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
              w.start()
              File "D:\Program Files (x86)\QGIS\apps\Python37\lib\multiprocessing\process.py", line 112, in start
              self._popen = self._Popen(self)
              File "D:\Program Files (x86)\QGIS\apps\Python37\lib\multiprocessing\context.py", line 322, in _Popen
              return Popen(process_obj)
              File "D:\Program Files (x86)\QGIS\apps\Python37\lib\multiprocessing\popen_spawn_win32.py", line 48, in __init__
              None, None, False, 0, None, None, None)
             FileNotFoundError: [WinError 2] The system cannot find the specified file.

**Comment by sfkeller** [comment]
Hi, 

I fear that this is a plugin error. 
Pls. note that the "Vector-Tiles-Reader-QGIS-Plugin" has been superseeded since QGIS 3.14 version by a native support for loading of vector tiles. See e.g. https://docs.qgis.org/3.22/en/docs/user_manual/working_with_vector_tiles/vector_tiles_properties.html

Yours, Stefan

**Comment by mmmlynn** [comment]
已收到您的邮件。辛苦啦！
