### ISSUE TITLE
Couldn't load plugin, No module named 'imp' 

### ISSUE THREAD

**Issue by kudlav** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#296]
Couldn't load plugin 'vector_tiles_reader' due to an error when calling its classFactory() method 

```
ModuleNotFoundError: No module named 'imp' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS 3.36.2/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Vladan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\__init__.py", line 25, in classFactory
    from .plugin.vtr_plugin import VtrPlugin
  File "C:\PROGRA~1/QGIS 3.36.2/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Vladan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\vtr_plugin.py", line 31, in 
    from .style_converter import core
  File "C:\PROGRA~1/QGIS 3.36.2/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Vladan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\style_converter\core\__init__.py", line 12, in 
    from ...util.network_helper import http_get
  File "C:\PROGRA~1/QGIS 3.36.2/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Vladan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\util\network_helper.py", line 10, in 
    from .log_helper import info, remove_key, warn
  File "C:\PROGRA~1/QGIS 3.36.2/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Vladan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vector_tiles_reader\plugin\util\log_helper.py", line 103, in 
    from imp import reload
  File "C:\PROGRA~1/QGIS 3.36.2/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'imp'
```

Python version: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.36.2-Maidenhead Maidenhead, 6d250527 

Python Path:
- C:/PROGRA~1/QGIS 3.36.2/apps/qgis/./python
- C:/Users/Vladan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
- C:/Users/Vladan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
- C:/PROGRA~1/QGIS 3.36.2/apps/qgis/./python/plugins
- C:\PROGRA~1\QGIS 3.36.2\apps\grass\grass83\etc\python
- C:\Users\Vladan\Documents
- C:\Program Files\QGIS 3.36.2\bin\python312.zip
- C:\PROGRA~1\QGIS 3.36.2\apps\Python312\DLLs
- C:\PROGRA~1\QGIS 3.36.2\apps\Python312\Lib
- C:\Program Files\QGIS 3.36.2\bin
- C:\PROGRA~1\QGIS 3.36.2\apps\Python312
- C:\PROGRA~1\QGIS 3.36.2\apps\Python312\Lib\site-packages
- C:\PROGRA~1\QGIS 3.36.2\apps\Python312\Lib\site-packages\win32
- C:\PROGRA~1\QGIS 3.36.2\apps\Python312\Lib\site-packages\win32\lib
- C:\PROGRA~1\QGIS 3.36.2\apps\Python312\Lib\site-packages\Pythonwin
- C:/Users/Vladan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
- C:\Users\Vladan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\vector_tiles_reader\ext-libs

**Comment by sfkeller** [comment]
Similar issue as #295 . 

I'm sorry but this plugin is deprecated and not maintained. It's redundant as Tom said: https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/issues/295#issuecomment-1952954729 .
