### ISSUE TITLE
ValueError: substring not found

### ISSUE THREAD

**Issue by tomchadwin** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#37]
```
Traceback (most recent call last):
  File "C:/Users/tchadwin/.qgis2/python/plugins\Vector-Tiles-Reader-QGIS-Plugin\vtr_plugin.py", line 186, in _on_open_mbtiles
    self._load_tiles(path=path, options=self.file_dialog.options, extent_to_load=None)
  File "C:/Users/tchadwin/.qgis2/python/plugins\Vector-Tiles-Reader-QGIS-Plugin\vtr_plugin.py", line 222, in _load_tiles
    extent_to_load=extent_to_load)
  File "C:/Users/tchadwin/.qgis2/python/plugins\Vector-Tiles-Reader-QGIS-Plugin\vt_reader.py", line 175, in load_tiles
    apply_styles=apply_styles)
  File "C:/Users/tchadwin/.qgis2/python/plugins\Vector-Tiles-Reader-QGIS-Plugin\vt_reader.py", line 273, in _create_qgis_layer_hierarchy
    layer = self._add_vector_layer(file_src, layer_name, target_group, layer_path, merge_features)
  File "C:/Users/tchadwin/.qgis2/python/plugins\Vector-Tiles-Reader-QGIS-Plugin\vt_reader.py", line 367, in _add_vector_layer
    if self.source.name().lower().index("openmaptiles") != -1:
ValueError: substring not found
```

**Comment by mnboos** [comment]
Thank you, fixed it. Out of curiosity: what are you using as tileservice?

**Comment by sfkeller** [comment]
(@tomchadwin Just out of gratitude I'd like to thank you for your efforts in your engagement for this plugin :-) )

**Comment by tomchadwin** [comment]
@mnboos I followed your instructions to download a citywide .mbtiles from OpenMapTiles.

**Comment by tomchadwin** [comment]
@sfkeller You are very welcome indeed - thanks for saying that! But my motives are selfish - I see this plugin as a potential way to have vector tiles supported by qgis2web. But also, I have had so much help from others with qgis2web, that tiny little contributions like this are the least I can do to give back.

Keep up the great work!

**Comment by tomchadwin** [comment]
Confirmed fixed - thanks!
