### ISSUE TITLE
ValueError: math domain error 

### ISSUE THREAD

**Issue by pnorman** [geometalab/Vector-Tiles-Reader-QGIS-Plugin#81]
When I try to add a layer I get the error

```
An error has occurred while executing Python code: 

ValueError: math domain error 
Traceback (most recent call last):
  File "C:/Users/pnorman/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 202, in _on_add_layer
    bounds = self._current_reader.source.bounds_tile(zoom)
  File "C:/Users/pnorman/.qgis2/python/plugins\vector_tiles_reader\tile_source.py", line 73, in bounds_tile
    return self.json.bounds_tile(zoom)
  File "C:/Users/pnorman/.qgis2/python/plugins\vector_tiles_reader\tile_json.py", line 85, in bounds_tile
    return get_tile_bounds(zoom, bounds, crs, scheme)
  File "C:/Users/pnorman/.qgis2/python/plugins\vector_tiles_reader\tile_helper.py", line 115, in get_tile_bounds
    xy_max = latlon_to_tile(zoom, lat_min, lng_max, scheme)
  File "C:/Users/pnorman/.qgis2/python/plugins\vector_tiles_reader\tile_helper.py", line 45, in latlon_to_tile
    m = gm.LatLonToMeters(lat, lng)
  File "C:/Users/pnorman/.qgis2/python/plugins\vector_tiles_reader\global_map_tiles.py", line 180, in LatLonToMeters
    my = math.log(math.tan((90 + lat) * math.pi / 360.0)) / (math.pi / 180.0)
ValueError: math domain error


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.2 Las Palmas, 102ee87 

Python Path:
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
C:/Users/pnorman/.qgis2/python
C:/Users/pnorman/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/pnorman/.qgis2//python
C:\Users\pnorman\.qgis2\python\plugins\vector_tiles_reader\ext-libs
```

Previous screen was

![image](https://user-images.githubusercontent.com/1190866/30889499-9aa4bada-a2db-11e7-947e-00ce23d8c237.png)

vector_demo.json is

```json
{
    "attribution": "",
    "bounds": [
        -180,
        -90,
        180,
        90
    ],
    "center": [
        0,
        0,
        0
    ],
    "data": [],
    "description": null,
    "format": "pbf",
    "grids": [],
    "legend": null,
    "maxzoom": 5,
    "minzoom": 0,
    "name": "vector_demo",
    "scheme": "xyz",
    "template": null,
    "tilejson": "2.1.0",
    "tiles": [
        "http://192.168.1.1:9090/maps/vector_demo/{z}/{x}/{y}.pbf"
    ],
    "vector_layers": [
        {
            "extent": 4096,
            "feature_tags": null,
            "geometry_type": null,
            "id": "water-lz",
            "maxzoom": 5,
            "minzoom": 0,
            "name": "water-lz",
            "tiles": [
                "http://192.168.1.1:9090/maps/vector_demo/water-lz/{z}/{x}/{y}.pbf"
            ],
            "version": 2
        }
    ],
    "version": "1.0.0"
}
```

**Comment by sfkeller** [comment]
Yeah, that's a bug. Could be provoked though by 
1. `"bounds": [-180, -90, 180, 90]` instead non-overlapping numbers like `"bounds": [-180, -85, 180, 85]`?
2. Missing line  `"pixel_scale": "256",` ?

**Comment by pnorman** [comment]
If I change the bounds to `[ -180, -85.05112877980659, 180, 85.0511287798066 ]` I no longer get **this** domain error.

`[-180, -90, 180, 90]` is explicitly an acceptable value in the tilejson spec, and is the default value, so should be equivalent to specifying no bounds.

> Missing line "pixel_scale": "256", ?

There's no reason to expect this line, it's not part of the spec so not required.


-----

I mentioned I no longer get **this** domain error after changing the bounds, but now when I add it I get an error after it loads

![image](https://user-images.githubusercontent.com/1190866/30890433-c851ed44-a2e1-11e7-8977-81fc3b7d77f0.png)

The traceback is 

```
ValueError: math domain error 
Traceback (most recent call last):
  File "C:/Users/pnorman/.qgis2/python/plugins\vector_tiles_reader\vtr_plugin.py", line 58, in _handle_mouse_move
    tile = latlon_to_tile(zoom, lat_lon[0], lat_lon[1])
  File "C:/Users/pnorman/.qgis2/python/plugins\vector_tiles_reader\tile_helper.py", line 45, in latlon_to_tile
    m = gm.LatLonToMeters(lat, lng)
  File "C:/Users/pnorman/.qgis2/python/plugins\vector_tiles_reader\global_map_tiles.py", line 180, in LatLonToMeters
    my = math.log(math.tan((90 + lat) * math.pi / 360.0)) / (math.pi / 180.0)
ValueError: math domain error
```

The data does load, but there's an error with some landmasses missing

![image](https://user-images.githubusercontent.com/1190866/30890465-fc0c1394-a2e1-11e7-9488-a39ee8b6c71f.png)

I don't know if the error is caused by the plugin or Tegola.

**Comment by sfkeller** [comment]
pnorman :Thanks for testing with Tegola. You wrote elsewhere:

> If you need it I can download z0-z5 of this source and you can put it up somewhere so you can test yourself

Yes, please. That could eventually also be an mbtiles file (though not quite the same as an online "Connection"). Beware that the plugin assumes to get metadata, especially about the bounds.

**Comment by pnorman** [comment]
I've only included z0-z3, and a tilejson file is included in the archive.
[tegola_tiles.zip](https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/files/1336331/tegola_tiles.zip)

I've opened #terranodo/tegola#150 since I'm reasonably confident the water flood is an issue with tegola, but the domain error remains a problem.

**Comment by mnboos** [comment]
Fixed. Will be included in the next release.
